#pragma once

enum Tiles
{
    PATH_CORNER_TL=0, PATH_CENTER_TOP=1, PATH_CORNER_TR=2, PATH_END_TOP=4,

    TREE_UPL=4,
    TREE_UPC=5,
    TREE_UPR=6,

    TREE_MDL=14,
    TREE_MDC=15,
    TREE_MDR=16,

    TREE_LOL=24,
    TREE_LOC=25,
    TREE_LOR=26,

    PATH_SIDE_LEFT=10, PATH_CENTER=11, PATH_SIDE_RIGHT=12, PATH_VERT_CENTER=13,

    PATH_CORNER_BL=20, PATH_CENTER_BOTTOM=21, PATH_CORNER_BR=22, PATH_END_BOTTOM=23,

    PATH_END_LEFT=30, PATH_HORIZ_CENTER=31, PATH_END_RIGHT=32, GROUND=33,
    CLIFF_TOP=39,
    CLIFF_BOT=49,

    WOOD_PTR=56,

    GROUND_SPOT_A=40, GROUND_SPOT_B=41,
};

static int mapData[400]
{
    CLIFF_TOP, CLIFF_TOP, CLIFF_TOP, CLIFF_TOP, CLIFF_TOP,
    CLIFF_TOP, CLIFF_TOP, CLIFF_TOP, CLIFF_TOP, CLIFF_TOP,
    CLIFF_TOP, CLIFF_TOP, CLIFF_TOP, CLIFF_TOP, CLIFF_TOP,
    CLIFF_TOP, CLIFF_TOP, CLIFF_TOP, CLIFF_TOP, CLIFF_TOP,

    CLIFF_BOT, CLIFF_BOT, CLIFF_BOT, CLIFF_BOT, CLIFF_BOT,
    CLIFF_BOT, CLIFF_BOT, CLIFF_BOT, CLIFF_BOT, CLIFF_BOT,
    CLIFF_BOT, CLIFF_BOT, CLIFF_BOT, CLIFF_BOT, CLIFF_BOT,
    CLIFF_BOT, CLIFF_BOT, CLIFF_BOT, CLIFF_BOT, CLIFF_BOT,

    TREE_UPL, TREE_UPC, TREE_UPR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_MDL, TREE_MDC, TREE_MDR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_LOL, TREE_LOC, TREE_LOR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_UPL, TREE_UPC, TREE_UPR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_MDL, TREE_MDC, TREE_MDR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_LOL, TREE_LOC, TREE_LOR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_UPL, TREE_UPC, TREE_UPR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_MDL, TREE_MDC, TREE_MDR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_LOL, TREE_LOC, TREE_LOR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_UPL, TREE_UPC, TREE_UPR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_MDL, TREE_MDC, TREE_MDR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_LOL, TREE_LOC, TREE_LOR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_UPL, TREE_UPC, TREE_UPR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_MDL, TREE_MDC, TREE_MDR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_LOL, TREE_LOC, TREE_LOR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_UPL, TREE_UPC, TREE_UPR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_MDL, TREE_MDC, TREE_MDR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

    TREE_LOL, TREE_LOC, TREE_LOR, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, GROUND,
    GROUND, GROUND, GROUND, GROUND, WOOD_PTR,

};
